################################################## 
# MoodleWS_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from MoodleWS_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class MoodleWSLocator:
    MoodleWSPortType_address = "http://cipcnet.insa-lyon.fr/moodle/wspp/service_pp.php"
    def getMoodleWSPortTypeAddress(self):
        return MoodleWSLocator.MoodleWSPortType_address
    def getMoodleWSPortType(self, url=None, **kw):
        return MoodleWSBindingSOAP(url or MoodleWSLocator.MoodleWSPortType_address, **kw)

# Methods
class MoodleWSBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: login
    def login(self, request):
        if isinstance(request, loginRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#login", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=loginResponse.typecode.ofwhat, pyclass=loginResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: logout
    def logout(self, request):
        if isinstance(request, logoutRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#logout", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=logoutResponse.typecode.ofwhat, pyclass=logoutResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: edit_users
    def edit_users(self, request):
        if isinstance(request, edit_usersRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#edit_users", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=edit_usersResponse.typecode.ofwhat, pyclass=edit_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_users
    def get_users(self, request):
        if isinstance(request, get_usersRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_users", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: edit_courses
    def edit_courses(self, request):
        if isinstance(request, edit_coursesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#edit_courses", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=edit_coursesResponse.typecode.ofwhat, pyclass=edit_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_courses
    def get_courses(self, request):
        if isinstance(request, get_coursesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_courses", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_grades
    def get_grades(self, request):
        if isinstance(request, get_gradesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_grades", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_gradesResponse.typecode.ofwhat, pyclass=get_gradesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: enrol_students
    def enrol_students(self, request):
        if isinstance(request, enrol_studentsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#enrol_students", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=enrol_studentsResponse.typecode.ofwhat, pyclass=enrol_studentsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_last_changes
    def get_last_changes(self, request):
        if isinstance(request, get_last_changesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_last_changes", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_last_changesResponse.typecode.ofwhat, pyclass=get_last_changesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_events
    def get_events(self, request):
        if isinstance(request, get_eventsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_events", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_eventsResponse.typecode.ofwhat, pyclass=get_eventsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_course
    def get_course(self, request):
        if isinstance(request, get_courseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_course", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_course_byid
    def get_course_byid(self, request):
        if isinstance(request, get_course_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_course_byid", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_course_byidnumber
    def get_course_byidnumber(self, request):
        if isinstance(request, get_course_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_course_byidnumber", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_user
    def get_user(self, request):
        if isinstance(request, get_userRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_user", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_roles
    def get_roles(self, request):
        if isinstance(request, noinputRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_roles", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_rolesResponse.typecode.ofwhat, pyclass=get_rolesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_role_byid
    def get_role_byid(self, request):
        if isinstance(request, oneValueRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_role_byid", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_rolesResponse.typecode.ofwhat, pyclass=get_rolesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_role_byname
    def get_role_byname(self, request):
        if isinstance(request, oneValueRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_role_byname", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_rolesResponse.typecode.ofwhat, pyclass=get_rolesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_categories
    def get_categories(self, request):
        if isinstance(request, noinputRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_categories", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_categoriesResponse.typecode.ofwhat, pyclass=get_categoriesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_category_byid
    def get_category_byid(self, request):
        if isinstance(request, oneValueRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_category_byid", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_categoriesResponse.typecode.ofwhat, pyclass=get_categoriesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_category_byname
    def get_category_byname(self, request):
        if isinstance(request, oneValueRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_category_byname", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_categoriesResponse.typecode.ofwhat, pyclass=get_categoriesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_courses
    def get_my_courses(self, request):
        if isinstance(request, get_my_coursesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_courses", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_courses_byusername
    def get_my_courses_byusername(self, request):
        if isinstance(request, get_my_courses_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_courses_byusername", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_courses_byidnumber
    def get_my_courses_byidnumber(self, request):
        if isinstance(request, get_my_courses_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_courses_byidnumber", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_user_byusername
    def get_user_byusername(self, request):
        if isinstance(request, get_user_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_user_byusername", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_user_byidnumber
    def get_user_byidnumber(self, request):
        if isinstance(request, get_user_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_user_byidnumber", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_user_byid
    def get_user_byid(self, request):
        if isinstance(request, get_user_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_user_byid", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_users_bycourse
    def get_users_bycourse(self, request):
        if isinstance(request, get_users_bycourseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_users_bycourse", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: count_users_bycourse
    def count_users_bycourse(self, request):
        if isinstance(request, get_users_bycourseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#count_users_bycourse", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=integerResponse.typecode.ofwhat, pyclass=integerResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_courses_bycategory
    def get_courses_bycategory(self, request):
        if isinstance(request, get_courses_bycategoryRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_courses_bycategory", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_coursesResponse.typecode.ofwhat, pyclass=get_coursesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_groups_bycourse
    def get_groups_bycourse(self, request):
        if isinstance(request, get_groups_bycourseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_groups_bycourse", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_groupsResponse.typecode.ofwhat, pyclass=get_groupsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_group_byid
    def get_group_byid(self, request):
        if isinstance(request, get_group_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_group_byid", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_groupsResponse.typecode.ofwhat, pyclass=get_groupsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_groups_byname
    def get_groups_byname(self, request):
        if isinstance(request, get_group_byRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_groups_byname", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_groupsResponse.typecode.ofwhat, pyclass=get_groupsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_group_members
    def get_group_members(self, request):
        if isinstance(request, get_group_membersRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_group_members", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_id
    def get_my_id(self, request):
        if isinstance(request, noinputRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_id", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=integerResponse.typecode.ofwhat, pyclass=integerResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_group
    def get_my_group(self, request):
        if isinstance(request, get_my_groupRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_group", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_groupsResponse.typecode.ofwhat, pyclass=get_groupsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_my_groups
    def get_my_groups(self, request):
        if isinstance(request, get_my_groupsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_my_groups", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_groupsResponse.typecode.ofwhat, pyclass=get_groupsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_teachers
    def get_teachers(self, request):
        if isinstance(request, valueAndIdRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_teachers", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_students
    def get_students(self, request):
        if isinstance(request, valueAndIdRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_students", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_usersResponse.typecode.ofwhat, pyclass=get_usersResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: has_role_incourse
    def has_role_incourse(self, request):
        if isinstance(request, has_role_incourseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#has_role_incourse", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=booleanResponse.typecode.ofwhat, pyclass=booleanResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_primaryrole_incourse
    def get_primaryrole_incourse(self, request):
        if isinstance(request, get_primaryrole_incourseRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_primaryrole_incourse", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=integerResponse.typecode.ofwhat, pyclass=integerResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: get_activities
    def get_activities(self, request):
        if isinstance(request, get_activitiesRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#get_activities", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=get_activitiesResponse.typecode.ofwhat, pyclass=get_activitiesResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: count_activities
    def count_activities(self, request):
        if isinstance(request, twoValuesAndIdsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl#count_activities", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=integerResponse.typecode.ofwhat, pyclass=integerResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

_loginRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","login"), ofwhat=[ZSI.TC.String(pname="username", aname="_username", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="password", aname="_password", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class loginRequest:
    typecode = _loginRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._username = None
        self._password = None
        return
loginRequest.typecode.pyclass = loginRequest

_loginResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","loginResponse"), ofwhat=[ns0.loginReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class loginResponse:
    typecode = _loginResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
loginResponse.typecode.pyclass = loginResponse

_logoutRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","logout"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class logoutRequest:
    typecode = _logoutRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        return
logoutRequest.typecode.pyclass = logoutRequest

_logoutResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","logoutResponse"), ofwhat=[ZSI.TC.Boolean(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class logoutResponse:
    typecode = _logoutResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
logoutResponse.typecode.pyclass = logoutResponse

_edit_usersRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","edit_users"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.editUsersInput_Def(pname="users", aname="_users", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class edit_usersRequest:
    typecode = _edit_usersRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._users = None
        return
edit_usersRequest.typecode.pyclass = edit_usersRequest

_edit_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","edit_usersResponse"), ofwhat=[ns0.editUsersOutput_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class edit_usersResponse:
    typecode = _edit_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
edit_usersResponse.typecode.pyclass = edit_usersResponse

_get_usersRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_users"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.getUsersInput_Def(pname="userids", aname="_userids", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersRequest:
    typecode = _get_usersRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userids = None
        self._idfield = None
        return
get_usersRequest.typecode.pyclass = get_usersRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_usersResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_edit_coursesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","edit_courses"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.editCoursesInput_Def(pname="courses", aname="_courses", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class edit_coursesRequest:
    typecode = _edit_coursesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courses = None
        return
edit_coursesRequest.typecode.pyclass = edit_coursesRequest

_edit_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","edit_coursesResponse"), ofwhat=[ns0.editCoursesOutput_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class edit_coursesResponse:
    typecode = _edit_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
edit_coursesResponse.typecode.pyclass = edit_coursesResponse

_get_coursesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_courses"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.getCoursesInput_Def(pname="courseids", aname="_courseids", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesRequest:
    typecode = _get_coursesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseids = None
        self._idfield = None
        return
get_coursesRequest.typecode.pyclass = get_coursesRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_coursesResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_gradesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_grades"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="userid", aname="_userid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.getGradesInput_Def(pname="courseids", aname="_courseids", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_gradesRequest:
    typecode = _get_gradesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userid = None
        self._courseids = None
        self._idfield = None
        return
get_gradesRequest.typecode.pyclass = get_gradesRequest

_get_gradesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_gradesResponse"), ofwhat=[ns0.getGradesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_gradesResponse:
    typecode = _get_gradesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_gradesResponse.typecode.pyclass = get_gradesResponse

_enrol_studentsRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","enrol_students"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ns0.enrolStudentsInput_Def(pname="userids", aname="_userids", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class enrol_studentsRequest:
    typecode = _enrol_studentsRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseid = None
        self._userids = None
        self._idfield = None
        return
enrol_studentsRequest.typecode.pyclass = enrol_studentsRequest

_enrol_studentsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","enrol_studentsResponse"), ofwhat=[ns0.enrolStudentsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class enrol_studentsResponse:
    typecode = _enrol_studentsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
enrol_studentsResponse.typecode.pyclass = enrol_studentsResponse

_get_last_changesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_last_changes"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="limit", aname="_limit", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_last_changesRequest:
    typecode = _get_last_changesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseid = None
        self._idfield = None
        self._limit = None
        return
get_last_changesRequest.typecode.pyclass = get_last_changesRequest

_get_last_changesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_last_changesResponse"), ofwhat=[ns0.getLastChangesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_last_changesResponse:
    typecode = _get_last_changesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_last_changesResponse.typecode.pyclass = get_last_changesResponse

_get_eventsRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_events"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="eventtype", aname="_eventtype", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="ownerid", aname="_ownerid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_eventsRequest:
    typecode = _get_eventsRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._eventtype = None
        self._ownerid = None
        return
get_eventsRequest.typecode.pyclass = get_eventsRequest

_get_eventsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_eventsResponse"), ofwhat=[ns0.getEventsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_eventsResponse:
    typecode = _get_eventsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_eventsResponse.typecode.pyclass = get_eventsResponse

_get_courseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_course"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_courseRequest:
    typecode = _get_courseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseid = None
        self._idfield = None
        return
get_courseRequest.typecode.pyclass = get_courseRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_courseResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_course_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_course_byid"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="info", aname="_info", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_course_byRequest:
    typecode = _get_course_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._info = None
        return
get_course_byRequest.typecode.pyclass = get_course_byRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_course_byidResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_course_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_course_byidnumber"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="info", aname="_info", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_course_byRequest:
    typecode = _get_course_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._info = None
        return
get_course_byRequest.typecode.pyclass = get_course_byRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_course_byidnumberResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_userRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="userid", aname="_userid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_userRequest:
    typecode = _get_userRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userid = None
        self._idfield = None
        return
get_userRequest.typecode.pyclass = get_userRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_userResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_noinputRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_roles"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class noinputRequest:
    typecode = _noinputRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        return
noinputRequest.typecode.pyclass = noinputRequest

_get_rolesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_rolesResponse"), ofwhat=[ns0.getRolesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_rolesResponse:
    typecode = _get_rolesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_rolesResponse.typecode.pyclass = get_rolesResponse

_oneValueRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_role_byid"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class oneValueRequest:
    typecode = _oneValueRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        return
oneValueRequest.typecode.pyclass = oneValueRequest

_get_rolesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_role_byidResponse"), ofwhat=[ns0.getRolesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_rolesResponse:
    typecode = _get_rolesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_rolesResponse.typecode.pyclass = get_rolesResponse

_oneValueRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_role_byname"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class oneValueRequest:
    typecode = _oneValueRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        return
oneValueRequest.typecode.pyclass = oneValueRequest

_get_rolesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_role_bynameResponse"), ofwhat=[ns0.getRolesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_rolesResponse:
    typecode = _get_rolesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_rolesResponse.typecode.pyclass = get_rolesResponse

_noinputRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_categories"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class noinputRequest:
    typecode = _noinputRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        return
noinputRequest.typecode.pyclass = noinputRequest

_get_categoriesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_categoriesResponse"), ofwhat=[ns0.getCategoriesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_categoriesResponse:
    typecode = _get_categoriesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_categoriesResponse.typecode.pyclass = get_categoriesResponse

_oneValueRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_category_byid"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class oneValueRequest:
    typecode = _oneValueRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        return
oneValueRequest.typecode.pyclass = oneValueRequest

_get_categoriesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_category_byidResponse"), ofwhat=[ns0.getCategoriesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_categoriesResponse:
    typecode = _get_categoriesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_categoriesResponse.typecode.pyclass = get_categoriesResponse

_oneValueRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_category_byname"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class oneValueRequest:
    typecode = _oneValueRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        return
oneValueRequest.typecode.pyclass = oneValueRequest

_get_categoriesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_category_bynameResponse"), ofwhat=[ns0.getCategoriesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_categoriesResponse:
    typecode = _get_categoriesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_categoriesResponse.typecode.pyclass = get_categoriesResponse

_get_my_coursesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_courses"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="uid", aname="_uid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sort", aname="_sort", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_my_coursesRequest:
    typecode = _get_my_coursesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._uid = None
        self._sort = None
        return
get_my_coursesRequest.typecode.pyclass = get_my_coursesRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_coursesResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_my_courses_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_courses_byusername"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="uinfo", aname="_uinfo", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sort", aname="_sort", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_my_courses_byRequest:
    typecode = _get_my_courses_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._uinfo = None
        self._sort = None
        return
get_my_courses_byRequest.typecode.pyclass = get_my_courses_byRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_courses_byusernameResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_my_courses_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_courses_byidnumber"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="uinfo", aname="_uinfo", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sort", aname="_sort", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_my_courses_byRequest:
    typecode = _get_my_courses_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._uinfo = None
        self._sort = None
        return
get_my_courses_byRequest.typecode.pyclass = get_my_courses_byRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_courses_byidnumberResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_user_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byusername"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="userinfo", aname="_userinfo", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_user_byRequest:
    typecode = _get_user_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userinfo = None
        return
get_user_byRequest.typecode.pyclass = get_user_byRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byusernameResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_get_user_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byidnumber"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="userinfo", aname="_userinfo", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_user_byRequest:
    typecode = _get_user_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userinfo = None
        return
get_user_byRequest.typecode.pyclass = get_user_byRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byidnumberResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_get_user_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byid"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="userinfo", aname="_userinfo", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_user_byRequest:
    typecode = _get_user_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._userinfo = None
        return
get_user_byRequest.typecode.pyclass = get_user_byRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_user_byidResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_get_users_bycourseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_users_bycourse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcourse", aname="_idcourse", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="idrole", aname="_idrole", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_users_bycourseRequest:
    typecode = _get_users_bycourseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._idcourse = None
        self._idfield = None
        self._idrole = None
        return
get_users_bycourseRequest.typecode.pyclass = get_users_bycourseRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_users_bycourseResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_get_users_bycourseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","count_users_bycourse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcourse", aname="_idcourse", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="idrole", aname="_idrole", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_users_bycourseRequest:
    typecode = _get_users_bycourseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._idcourse = None
        self._idfield = None
        self._idrole = None
        return
get_users_bycourseRequest.typecode.pyclass = get_users_bycourseRequest

_integerResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","count_users_bycourseResponse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class integerResponse:
    typecode = _integerResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
integerResponse.typecode.pyclass = integerResponse

_get_courses_bycategoryRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_courses_bycategory"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="categoryid", aname="_categoryid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_courses_bycategoryRequest:
    typecode = _get_courses_bycategoryRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._categoryid = None
        return
get_courses_bycategoryRequest.typecode.pyclass = get_courses_bycategoryRequest

_get_coursesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_courses_bycategoryResponse"), ofwhat=[ns0.getCoursesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_coursesResponse:
    typecode = _get_coursesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_coursesResponse.typecode.pyclass = get_coursesResponse

_get_groups_bycourseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_groups_bycourse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idfield", aname="_idfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groups_bycourseRequest:
    typecode = _get_groups_bycourseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseid = None
        self._idfield = None
        return
get_groups_bycourseRequest.typecode.pyclass = get_groups_bycourseRequest

_get_groupsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_groups_bycourseResponse"), ofwhat=[ns0.getGroupsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groupsResponse:
    typecode = _get_groupsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_groupsResponse.typecode.pyclass = get_groupsResponse

_get_group_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_group_byid"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="info", aname="_info", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_group_byRequest:
    typecode = _get_group_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._info = None
        self._courseid = None
        return
get_group_byRequest.typecode.pyclass = get_group_byRequest

_get_groupsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_group_byidResponse"), ofwhat=[ns0.getGroupsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groupsResponse:
    typecode = _get_groupsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_groupsResponse.typecode.pyclass = get_groupsResponse

_get_group_byRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_groups_byname"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="info", aname="_info", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_group_byRequest:
    typecode = _get_group_byRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._info = None
        self._courseid = None
        return
get_group_byRequest.typecode.pyclass = get_group_byRequest

_get_groupsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_groups_bynameResponse"), ofwhat=[ns0.getGroupsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groupsResponse:
    typecode = _get_groupsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_groupsResponse.typecode.pyclass = get_groupsResponse

_get_group_membersRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_group_members"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="groupid", aname="_groupid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_group_membersRequest:
    typecode = _get_group_membersRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._groupid = None
        return
get_group_membersRequest.typecode.pyclass = get_group_membersRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_group_membersResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_noinputRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_id"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class noinputRequest:
    typecode = _noinputRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        return
noinputRequest.typecode.pyclass = noinputRequest

_integerResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_idResponse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class integerResponse:
    typecode = _integerResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
integerResponse.typecode.pyclass = integerResponse

_get_my_groupRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_group"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="courseid", aname="_courseid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="uid", aname="_uid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_my_groupRequest:
    typecode = _get_my_groupRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._courseid = None
        self._uid = None
        return
get_my_groupRequest.typecode.pyclass = get_my_groupRequest

_get_groupsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_groupResponse"), ofwhat=[ns0.getGroupsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groupsResponse:
    typecode = _get_groupsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_groupsResponse.typecode.pyclass = get_groupsResponse

_get_my_groupsRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_groups"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="uid", aname="_uid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_my_groupsRequest:
    typecode = _get_my_groupsRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._uid = None
        return
get_my_groupsRequest.typecode.pyclass = get_my_groupsRequest

_get_groupsResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_my_groupsResponse"), ofwhat=[ns0.getGroupsReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_groupsResponse:
    typecode = _get_groupsResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_groupsResponse.typecode.pyclass = get_groupsResponse

_valueAndIdRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_teachers"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class valueAndIdRequest:
    typecode = _valueAndIdRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        self._id = None
        return
valueAndIdRequest.typecode.pyclass = valueAndIdRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_teachersResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_valueAndIdRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_students"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value", aname="_value", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="id", aname="_id", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class valueAndIdRequest:
    typecode = _valueAndIdRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value = None
        self._id = None
        return
valueAndIdRequest.typecode.pyclass = valueAndIdRequest

_get_usersResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_studentsResponse"), ofwhat=[ns0.getUsersReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_usersResponse:
    typecode = _get_usersResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_usersResponse.typecode.pyclass = get_usersResponse

_has_role_incourseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","has_role_incourse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduser", aname="_iduser", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduserfield", aname="_iduserfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcourse", aname="_idcourse", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcoursefield", aname="_idcoursefield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="idrole", aname="_idrole", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class has_role_incourseRequest:
    typecode = _has_role_incourseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._iduser = None
        self._iduserfield = None
        self._idcourse = None
        self._idcoursefield = None
        self._idrole = None
        return
has_role_incourseRequest.typecode.pyclass = has_role_incourseRequest

_booleanResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","has_role_incourseResponse"), ofwhat=[ZSI.TC.Boolean(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class booleanResponse:
    typecode = _booleanResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
booleanResponse.typecode.pyclass = booleanResponse

_get_primaryrole_incourseRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_primaryrole_incourse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduser", aname="_iduser", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduserfield", aname="_iduserfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcourse", aname="_idcourse", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcoursefield", aname="_idcoursefield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_primaryrole_incourseRequest:
    typecode = _get_primaryrole_incourseRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._iduser = None
        self._iduserfield = None
        self._idcourse = None
        self._idcoursefield = None
        return
get_primaryrole_incourseRequest.typecode.pyclass = get_primaryrole_incourseRequest

_integerResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_primaryrole_incourseResponse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class integerResponse:
    typecode = _integerResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
integerResponse.typecode.pyclass = integerResponse

_get_activitiesRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_activities"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduser", aname="_iduser", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="iduserfield", aname="_iduserfield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcourse", aname="_idcourse", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="idcoursefield", aname="_idcoursefield", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.Iinteger(pname="idlimit", aname="_idlimit", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_activitiesRequest:
    typecode = _get_activitiesRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._iduser = None
        self._iduserfield = None
        self._idcourse = None
        self._idcoursefield = None
        self._idlimit = None
        return
get_activitiesRequest.typecode.pyclass = get_activitiesRequest

_get_activitiesResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","get_activitiesResponse"), ofwhat=[ns0.getActivitiesReturn_Def(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class get_activitiesResponse:
    typecode = _get_activitiesResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
get_activitiesResponse.typecode.pyclass = get_activitiesResponse

_twoValuesAndIdsRequestTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","count_activities"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="client", aname="_client", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="sesskey", aname="_sesskey", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value1", aname="_value1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="id1", aname="_id1", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="value2", aname="_value2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="id2", aname="_id2", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class twoValuesAndIdsRequest:
    typecode = _twoValuesAndIdsRequestTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._client = None
        self._sesskey = None
        self._value1 = None
        self._id1 = None
        self._value2 = None
        self._id2 = None
        return
twoValuesAndIdsRequest.typecode.pyclass = twoValuesAndIdsRequest

_integerResponseTypecode = Struct(pname=("http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl","count_activitiesResponse"), ofwhat=[ZSI.TCnumbers.Iinteger(pname="return", aname="_return", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=None, encoded="http://cipcnet.insa-lyon.fr/moodle/wspp/wsdl")
class integerResponse:
    typecode = _integerResponseTypecode
    __metaclass__ = pyclass_type
    def __init__(self):
        self._return = None
        return
integerResponse.typecode.pyclass = integerResponse
